import { withProps } from '@udecode/cn';
import { createPlugins, Plate, RenderAfterEditable, PlateLeaf } from '@udecode/plate-common';
import { createParagraphPlugin, ELEMENT_PARAGRAPH } from '@udecode/plate-paragraph';
import { createHeadingPlugin, ELEMENT_H1, ELEMENT_H2, ELEMENT_H3, ELEMENT_H4, ELEMENT_H5, ELEMENT_H6 } from '@udecode/plate-heading';
import { createBlockquotePlugin, ELEMENT_BLOCKQUOTE } from '@udecode/plate-block-quote';
import { createCodeBlockPlugin, ELEMENT_CODE_BLOCK, ELEMENT_CODE_LINE, ELEMENT_CODE_SYNTAX } from '@udecode/plate-code-block';
import { createHorizontalRulePlugin, ELEMENT_HR } from '@udecode/plate-horizontal-rule';
import { createLinkPlugin, ELEMENT_LINK } from '@udecode/plate-link';
import { createImagePlugin, ELEMENT_IMAGE, createMediaEmbedPlugin, ELEMENT_MEDIA_EMBED } from '@udecode/plate-media';
import { createCaptionPlugin } from '@udecode/plate-caption';
import { createMentionPlugin, ELEMENT_MENTION, ELEMENT_MENTION_INPUT } from '@udecode/plate-mention';
import { createTodoListPlugin, ELEMENT_TODO_LI } from '@udecode/plate-list';
import { createExcalidrawPlugin, ELEMENT_EXCALIDRAW } from '@udecode/plate-excalidraw';
import { createTogglePlugin, ELEMENT_TOGGLE } from '@udecode/plate-toggle';
import { createTablePlugin, ELEMENT_TABLE, ELEMENT_TR, ELEMENT_TD, ELEMENT_TH } from '@udecode/plate-table';
import { createBoldPlugin, MARK_BOLD, createItalicPlugin, MARK_ITALIC, createUnderlinePlugin, MARK_UNDERLINE, createStrikethroughPlugin, MARK_STRIKETHROUGH, createCodePlugin, MARK_CODE, createSubscriptPlugin, MARK_SUBSCRIPT, createSuperscriptPlugin, MARK_SUPERSCRIPT } from '@udecode/plate-basic-marks';
import { createFontColorPlugin, createFontBackgroundColorPlugin, createFontSizePlugin } from '@udecode/plate-font';
import { createHighlightPlugin, MARK_HIGHLIGHT } from '@udecode/plate-highlight';
import { createKbdPlugin, MARK_KBD } from '@udecode/plate-kbd';
import { createAlignPlugin } from '@udecode/plate-alignment';
import { createIndentPlugin } from '@udecode/plate-indent';
import { createIndentListPlugin } from '@udecode/plate-indent-list';
import { createLineHeightPlugin } from '@udecode/plate-line-height';
import { createAutoformatPlugin } from '@udecode/plate-autoformat';
import { createBlockSelectionPlugin } from '@udecode/plate-selection';
import { createComboboxPlugin } from '@udecode/plate-combobox';
import { createDndPlugin } from '@udecode/plate-dnd';
import { createEmojiPlugin } from '@udecode/plate-emoji';
import { createExitBreakPlugin, createSoftBreakPlugin } from '@udecode/plate-break';
import { createNodeIdPlugin } from '@udecode/plate-node-id';
import { createResetNodePlugin } from '@udecode/plate-reset-node';
import { createDeletePlugin } from '@udecode/plate-select';
import { createTabbablePlugin } from '@udecode/plate-tabbable';
import { createTrailingBlockPlugin } from '@udecode/plate-trailing-block';
import { createCommentsPlugin, CommentsProvider, MARK_COMMENT } from '@udecode/plate-comments';
import { createDeserializeDocxPlugin } from '@udecode/plate-serializer-docx';
import { createDeserializeCsvPlugin } from '@udecode/plate-serializer-csv';
import { createDeserializeMdPlugin } from '@udecode/plate-serializer-md';
import { createJuicePlugin } from '@udecode/plate-juice';
import { DndProvider } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';

import { BlockquoteElement } from '@/components/shadcn/plate-ui/blockquote-element';
import { CodeBlockElement } from '@/components/shadcn/plate-ui/code-block-element';
import { CodeLineElement } from '@/components/shadcn/plate-ui/code-line-element';
import { CodeSyntaxLeaf } from '@/components/shadcn/plate-ui/code-syntax-leaf';
import { ExcalidrawElement } from '@/components/shadcn/plate-ui/excalidraw-element';
import { HrElement } from '@/components/shadcn/plate-ui/hr-element';
import { ImageElement } from '@/components/shadcn/plate-ui/image-element';
import { LinkElement } from '@/components/shadcn/plate-ui/link-element';
import { LinkFloatingToolbar } from '@/components/shadcn/plate-ui/link-floating-toolbar';
import { ToggleElement } from '@/components/shadcn/plate-ui/toggle-element';
import { HeadingElement } from '@/components/shadcn/plate-ui/heading-element';
import { MediaEmbedElement } from '@/components/shadcn/plate-ui/media-embed-element';
import { MentionElement } from '@/components/shadcn/plate-ui/mention-element';
import { MentionInputElement } from '@/components/shadcn/plate-ui/mention-input-element';
import { MentionCombobox } from '@/components/shadcn/plate-ui/mention-combobox';
import { ParagraphElement } from '@/components/shadcn/plate-ui/paragraph-element';
import { TableElement } from '@/components/shadcn/plate-ui/table-element';
import { TableRowElement } from '@/components/shadcn/plate-ui/table-row-element';
import { TableCellElement, TableCellHeaderElement } from '@/components/shadcn/plate-ui/table-cell-element';
import { TodoListElement } from '@/components/shadcn/plate-ui/todo-list-element';
import { CodeLeaf } from '@/components/shadcn/plate-ui/code-leaf';
import { CommentLeaf } from '@/components/shadcn/plate-ui/comment-leaf';
import { CommentsPopover } from '@/components/shadcn/plate-ui/comments-popover';
import { HighlightLeaf } from '@/components/shadcn/plate-ui/highlight-leaf';
import { KbdLeaf } from '@/components/shadcn/plate-ui/kbd-leaf';
import { Editor } from '@/components/shadcn/plate-ui/editor';
import { FixedToolbar } from '@/components/shadcn/plate-ui/fixed-toolbar';
import { FixedToolbarButtons } from '@/components/shadcn/plate-ui/fixed-toolbar-buttons';
import { FloatingToolbar } from '@/components/shadcn/plate-ui/floating-toolbar';
import { FloatingToolbarButtons } from '@/components/shadcn/plate-ui/floating-toolbar-buttons';
import { withPlaceholders } from '@/components/shadcn/plate-ui/placeholder';
import { withDraggables } from '@/components/shadcn/plate-ui/with-draggables'; 
